[build]
  command = "flutter build web --release --web-renderer html"
  publish = "build/web"

[build.environment]
  FLUTTER_VERSION = "3.22.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-lighthouse"

[functions]
  directory = "netlify/functions"
