name: canton_connect
description: Canton Connect - Food Delivery App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core UI & State Management
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  
  # Navigation
  go_router: ^12.1.3
  
  # Storage & Networking
  shared_preferences: ^2.2.2
  http: ^1.1.0
  
  # Navigation & UI
  url_launcher: ^6.1.11
  image: ^4.0.17

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Utilities
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/translations/
    - assets/images/food_placeholder.png
    - assets/images/food_placeholder_2.png
    - assets/images/food_placeholder_3.png
    - assets/images/addon_placeholder.png
    - assets/images/drinks/lemon_tea.png
    - assets/images/drinks/coconut.png
    - assets/images/drinks/drink_placeholder.png
    - assets/images/foods/appetizers/spring_rolls.jpg        
    - assets/images/foods/appetizers/pork_dumplings.jpg   
    - assets/images/foods/seafood/steamed_fish.jpg   
    - assets/images/foods/seafood/kung_pao_shrimp.jpg     
    - assets/images/foods/main_course/kung_pao_chicken.jpg    
    - assets/images/foods/main_course/sweet_sour_pork.jpg     
    - assets/images/foods/main_course/beef_broccoli.jpg 
    - assets/images/foods/vegetarian/buddhas_delight.jpg     
    - assets/images/foods/vegetarian/mapo_tofu.jpg         
    - assets/images/foods/rice_noodles/yangzhou_rice.jpg       
    - assets/images/foods/rice_noodles/beef_chow_fun.jpg  
    - assets/images/foods/family_packages/family_feast.jpg        
    - assets/images/foods/family_packages/seafood_banquet.jpg 
    - assets/images/foods/desserts/mango_pudding.jpg       
    - assets/images/foods/desserts/sesame_balls.jpg   
    - assets/images/foods/drinks/bubble_tea.jpg          
    - assets/images/addons/extra_rice.jpg              
    - assets/images/addons/extra_sauce.jpg 
    - assets/images/hero/hero_dish.png
    - assets/images/hero/hero_dish_mobile.png
    - assets/images/hero/hero_dish2.png
    - assets/images/hero/hero_couple.png
    - assets/images/background/home_background.jpg
    - assets/images/background/app_background.jpg
    - assets/images/background/background.jpg
    - assets/images/background/cta_background.jpg
    - assets/images/background/back_ground_1.jpg
    - assets/images/signature/fish.jpg                    
    - assets/images/signature/pork.jpg                    
    - assets/images/signature/duck.jpg                    
    - assets/images/menu/kung_pao_chicken.jpg        
    - assets/images/menu/sweet_sour_pork.jpg         
    - assets/images/menu/mapo_tofu.jpg               
    - assets/images/menu/family_feast.jpg            
    - assets/images/menu/weekend_special.jpg         
    - assets/images/menu/bubble_tea.jpg              
    - assets/images/menu/mango_pudding.jpg           
    - assets/images/menu/hot_pot.jpg                 
    - assets/images/menu/steamed_fish.jpg            
    - assets/images/menu/vegetable_stir_fry.jpg
    - assets/images/menu/fried_rice.jpg              
    - assets/images/menu/spring_rolls.jpg  
    - assets/images/youth/chicken.jpg                 
    - assets/images/youth/shrimp.jpg      
    - assets/images/healthy/fish.jpg                    
    - assets/images/healthy/vegetables.jpg 
    - assets/images/desserts/mango.jpg                   
    - assets/images/desserts/eggtart.jpg                 
    - assets/images/desserts/redbean.jpg 
    - assets/images/family/combo_a.jpg                 
    - assets/images/family/combo_b.jpg                 
    - assets/images/icons/icon-192.png                
    - assets/images/icons/icon-512.png                
    - assets/images/pattern.png
    - assets/images/logo_white.png
    - assets/images/logo.png
    - assets/images/favicon.png
    - assets/images/default_avatar.png 
    - assets/translations/zh.json
    - assets/translations/en.json

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: NotoSansSC
      fonts:
        - asset: assets/fonts/NotoSansSC-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSansSC-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansSC-Bold.ttf
          weight: 700
    - family: Fallback
      fonts:
        - asset: assets/fonts/NotoSansSC-Regular.ttf
        